from _libs.azure_blob_connector import AzureBlobConnector
from _libs.scrapper_datagouv import DataGouvScrapper, DataGouvSOSMedecinScrapper, DataGouvTestCovidScrapper
from _libs.scrapper_insee import InseeScrapper
from _libs.processor_covidfigures import DailyCovidFiguresProcessor
from _libs.processor_ehpad import DailyEhpadFiguresProcessor
from _libs.processor_insee_death import WeeklyInseeDeathFigureProcessor
